# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
  identifier = "gallery"
  name = "作品"
  url = "/gallery/my-uploads/"
  weight = 3
  [main.params]
  icon = "photo"
    newtab = false

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "bilibili"
    name       = "Bilibili"
    url        = "https://bilibili.com/"

    [social.params]
        icon = "bilibili"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"

    [social.params]
        icon = "brand-twitter"
